os:
  - osx
  - linux
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - sudo ln -s -f $(which clang) /usr/bin/gcc
  - sudo ln -s -f $(which clang++) /usr/bin/g++
  - gcc -v && g++ -v
  - cargo build --verbose
  - cargo test -- --nocapture
  - cargo build --verbose --features debug_tflite
  - cargo test --features debug_tflite -- --nocapture
