os:
  - osx
  - linux
language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s -f $(which clang) /usr/bin/gcc ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -s -f $(which clang++) /usr/bin/g++ ; fi
  - gcc -v && g++ -v
  - cargo build --verbose
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo test -- --nocapture ; fi
  - cargo build --verbose --features debug_tflite
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo test --features debug_tflite -- --nocapture ; fi
