[package]
name = "tflite"
version = "0.1.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]

[dependencies]
cpp = "0.5"
env_logger = "0.5"
failure = "0.1"
libc = "0.2"
log = "0.4"
ndarray = "0.11"

[build-dependencies]
bindgen = "0.43"
cpp_build = "0.5"
curl = "0.4"
failure = "0.1"
flate2 = "1.0"
hex = "0.3"
reqwest = "0.9"
sha2 = "0.8"
tar = "0.4"
