[package]
name = "tflite"
version = "0.1.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]

[dependencies]
cpp = "0.5"
failure = "0.1"
ndarray = "0.11"

[build-dependencies]
bindgen = "0.43"
cpp_build = "0.5"
