[package]
name = "tflite"
version = "0.5.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]
exclude = ["src/model/stl/vector_impl.rs"]

description = "Rust bindings for TensorFlow Lite"
keywords = ["tensorflow", "tflite", "bindings"]
license = "MIT/Apache-2.0"
repository = "https://github.com/boncheolgu/tflite-rs"
readme = "README.md"
edition = "2018"

[dependencies]
cpp = "0.5"
# cpp_stl = { path = "./cpp_stl", version = "0.1" }
failure = "0.1"
libc = "0.2"
maybe-owned = "0.3"

[build-dependencies]
bart = "0.1"
bart_derive = "0.1"
bindgen = "0.50"
cpp_build = "0.5"
curl = "0.4"
failure = "0.1"
flate2 = "1.0"
hex = "0.3"
reqwest = "0.9"
sha2 = "0.8"
tar = "0.4"

[features]
debug_tflite = [] # use "libtensorflow-lite.a" built in debug mode
